export default {
  id: "heatmap-layer",
  type: "heatmap",
  source: "heatmap-data",
  maxzoom: 18,
  paint: {
    "heatmap-weight": {
      property: "intensity",
      type: "exponential",
      stops: [
        [0, 0],
        [1, 1],
      ],
    },
    "heatmap-intensity": 1,
    "heatmap-color": [
      "interpolate",
      ["linear"],
      ["heatmap-density"],
      0,
      "rgba(0, 0, 255, 0)",
      0.1,
      "royalblue",
      0.3,
      "cyan",
      0.5,
      "lime",
      0.7,
      "yellow",
      1,
      "red",
    ],
    "heatmap-radius": 20,
    "heatmap-opacity": 1,
  },
};
